/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.librerias.ImagenFondo;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
        
        try {
            pnlPrincipal.setBorder(new ImagenFondo());
        } catch (IOException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        menu.setVisible(false);
        
        wdwIngresoDeUsuario Ingreso = new wdwIngresoDeUsuario();
               
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
        int x  = (ancho / 2) - (Ingreso.getWidth() / 2);
        int y  = (alto / 2) - Ingreso.getHeight();
        
        Ingreso.setLocation(x, y);
        Ingreso.setVisible(true);
        pnlPrincipal.add(Ingreso);
        Ingreso.toFront();
    }
    
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("inventory/imagenes/logotipo.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuMovimiento = new javax.swing.JMenu();
        menuIngresarSuscripcion = new javax.swing.JMenuItem();
        menuIngresarSuscripcion1 = new javax.swing.JMenuItem();
        menuDescargaLecturas = new javax.swing.JMenuItem();
        menuIngresarLecturas = new javax.swing.JMenuItem();
        menuGeneracionDeCobros = new javax.swing.JMenuItem();
        menuMovimientoAbonos = new javax.swing.JMenuItem();
        menuCatalogo = new javax.swing.JMenu();
        menuEmpresas = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuProveedores = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuPenalizacion = new javax.swing.JMenuItem();
        menuContabilidad = new javax.swing.JMenu();
        menuPagos = new javax.swing.JMenuItem();
        menuContabilidadIngresoCobro = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReportesAbonos = new javax.swing.JMenu();
        menuReportesAbonosCliente = new javax.swing.JMenuItem();
        menuReportesAbonosRealizados = new javax.swing.JMenuItem();
        menuReportesContabilidad = new javax.swing.JMenu();
        menuReportesPagos = new javax.swing.JMenuItem();
        menuReportesCobrosPorFecha = new javax.swing.JMenuItem();
        menuReportesCreditosPendientes = new javax.swing.JMenuItem();
        menuReportesClientes = new javax.swing.JMenu();
        menuReportesBalanceAntiguedad = new javax.swing.JMenuItem();
        menuReportesMorosos = new javax.swing.JMenuItem();
        menuReportesMaestroUsuarios = new javax.swing.JMenuItem();
        menuReportesMorososMes = new javax.swing.JMenuItem();
        menuReportesFacturacion = new javax.swing.JMenu();
        menuReportesAjustes = new javax.swing.JMenuItem();
        menuReportesCierreDiario = new javax.swing.JMenuItem();
        menuReportesFacturacionMensual = new javax.swing.JMenuItem();
        menuReportesImpresionRecibos1 = new javax.swing.JMenuItem();
        menuReportesImpresionRecibos = new javax.swing.JMenuItem();
        menuReportesRecibosNoPagados = new javax.swing.JMenuItem();
        menuReportesLecturas = new javax.swing.JMenu();
        menuReportesHistorialLecturas = new javax.swing.JMenuItem();
        menuReportesBalanceAntiguedad1 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payments");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName("LaEconomicaInventario"); // NOI18N

        jLabel1.setText("Usuario:");

        txtUsuario.setText("Descripcion Usuario");

        menuMovimiento.setText("Movimiento");

        menuIngresarSuscripcion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuIngresarSuscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/historialCompras.png"))); // NOI18N
        menuIngresarSuscripcion.setText("Ingresar Suscripcion");
        menuIngresarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarSuscripcionActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuIngresarSuscripcion);

        menuIngresarSuscripcion1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuIngresarSuscripcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/archivo.png"))); // NOI18N
        menuIngresarSuscripcion1.setText("Ingresar Credito");
        menuIngresarSuscripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarSuscripcion1ActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuIngresarSuscripcion1);

        menuDescargaLecturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuDescargaLecturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/exportar.png"))); // NOI18N
        menuDescargaLecturas.setText("Descargar Lecturas");
        menuDescargaLecturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDescargaLecturasActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuDescargaLecturas);

        menuIngresarLecturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuIngresarLecturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/nuevo.png"))); // NOI18N
        menuIngresarLecturas.setText("Ingreso de Lecturas");
        menuIngresarLecturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarLecturasActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuIngresarLecturas);

        menuGeneracionDeCobros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        menuGeneracionDeCobros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/exportar.png"))); // NOI18N
        menuGeneracionDeCobros.setText("Generacion de Cobros");
        menuGeneracionDeCobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGeneracionDeCobrosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuGeneracionDeCobros);

        menuMovimientoAbonos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuMovimientoAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/coins.png"))); // NOI18N
        menuMovimientoAbonos.setText("Abonos por Cliente");
        menuMovimientoAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovimientoAbonosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuMovimientoAbonos);

        menu.add(menuMovimiento);

        menuCatalogo.setText("Catalogo");
        menuCatalogo.setToolTipText("");

        menuEmpresas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menuEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        menuEmpresas.setText("Empresas");
        menuEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresasActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuEmpresas);

        menuCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/manual.png"))); // NOI18N
        menuCategorias.setText("Categorias");
        menuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriasActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuCategorias);

        menuProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/productos.png"))); // NOI18N
        menuProductos.setText("Servicios");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuProductos);
        menuCatalogo.add(jSeparator1);

        menuProveedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/clientes.png"))); // NOI18N
        menuProveedores.setText("Usuarios");
        menuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedoresActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuProveedores);

        menuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/proveedores.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setToolTipText("Ingreso de Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuClientes);

        menuPenalizacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuPenalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/agente.png"))); // NOI18N
        menuPenalizacion.setText("Penalizacion");
        menuPenalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenalizacionActionPerformed(evt);
            }
        });
        menuCatalogo.add(menuPenalizacion);

        menu.add(menuCatalogo);

        menuContabilidad.setText("Contabilidad");

        menuPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/spending.png"))); // NOI18N
        menuPagos.setText("Pagos");
        menuPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagosActionPerformed(evt);
            }
        });
        menuContabilidad.add(menuPagos);

        menuContabilidadIngresoCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/cobro.png"))); // NOI18N
        menuContabilidadIngresoCobro.setText("Cobros");
        menuContabilidadIngresoCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContabilidadIngresoCobroActionPerformed(evt);
            }
        });
        menuContabilidad.add(menuContabilidadIngresoCobro);

        menu.add(menuContabilidad);

        menuReportes.setText("Reportes");

        menuReportesAbonos.setText("Abonos");

        menuReportesAbonosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesAbonosCliente.setText("Abonos por Cliente");
        menuReportesAbonosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesAbonosClienteActionPerformed(evt);
            }
        });
        menuReportesAbonos.add(menuReportesAbonosCliente);

        menuReportesAbonosRealizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesAbonosRealizados.setText("Abonos Recibidos");
        menuReportesAbonosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesAbonosRealizadosActionPerformed(evt);
            }
        });
        menuReportesAbonos.add(menuReportesAbonosRealizados);

        menuReportes.add(menuReportesAbonos);

        menuReportesContabilidad.setText("Contabilidad");

        menuReportesPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesPagos.setText("Pagos por Fecha");
        menuReportesPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesPagosActionPerformed(evt);
            }
        });
        menuReportesContabilidad.add(menuReportesPagos);

        menuReportesCobrosPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesCobrosPorFecha.setText("Cobros por Fecha");
        menuReportesCobrosPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesCobrosPorFechaActionPerformed(evt);
            }
        });
        menuReportesContabilidad.add(menuReportesCobrosPorFecha);

        menuReportesCreditosPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesCreditosPendientes.setText("Creditos Pendientes");
        menuReportesCreditosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesCreditosPendientesActionPerformed(evt);
            }
        });
        menuReportesContabilidad.add(menuReportesCreditosPendientes);

        menuReportes.add(menuReportesContabilidad);

        menuReportesClientes.setText("Clientes");

        menuReportesBalanceAntiguedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesBalanceAntiguedad.setText("Balance de Antiguedad");
        menuReportesBalanceAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesBalanceAntiguedadActionPerformed(evt);
            }
        });
        menuReportesClientes.add(menuReportesBalanceAntiguedad);

        menuReportesMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesMorosos.setText("Clientes Morosos");
        menuReportesMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesMorososActionPerformed(evt);
            }
        });
        menuReportesClientes.add(menuReportesMorosos);

        menuReportesMaestroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesMaestroUsuarios.setText("Listado de Clientes");
        menuReportesMaestroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesMaestroUsuariosActionPerformed(evt);
            }
        });
        menuReportesClientes.add(menuReportesMaestroUsuarios);

        menuReportesMorososMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesMorososMes.setText("Morosos por Mes");
        menuReportesMorososMes.setToolTipText("");
        menuReportesMorososMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesMorososMesActionPerformed(evt);
            }
        });
        menuReportesClientes.add(menuReportesMorososMes);

        menuReportes.add(menuReportesClientes);

        menuReportesFacturacion.setText("Facturacion");

        menuReportesAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesAjustes.setText("Ajustes");
        menuReportesAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesAjustesActionPerformed(evt);
            }
        });
        menuReportesFacturacion.add(menuReportesAjustes);

        menuReportesCierreDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesCierreDiario.setText("Cierre Diario");
        menuReportesCierreDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesCierreDiarioActionPerformed(evt);
            }
        });
        menuReportesFacturacion.add(menuReportesCierreDiario);

        menuReportesFacturacionMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesFacturacionMensual.setText("Facturacion Mensual");
        menuReportesFacturacionMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesFacturacionMensualActionPerformed(evt);
            }
        });
        menuReportesFacturacion.add(menuReportesFacturacionMensual);

        menuReportesImpresionRecibos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesImpresionRecibos1.setText("Impresion de Avisos");
        menuReportesImpresionRecibos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesImpresionRecibos1ActionPerformed(evt);
            }
        });
        menuReportesFacturacion.add(menuReportesImpresionRecibos1);

        menuReportesImpresionRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesImpresionRecibos.setText("Impresion de Facturas");
        menuReportesImpresionRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesImpresionRecibosActionPerformed(evt);
            }
        });
        menuReportesFacturacion.add(menuReportesImpresionRecibos);

        menuReportesRecibosNoPagados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesRecibosNoPagados.setText("Listado de Recibos");
        menuReportesRecibosNoPagados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesRecibosNoPagadosActionPerformed(evt);
            }
        });
        menuReportesFacturacion.add(menuReportesRecibosNoPagados);

        menuReportes.add(menuReportesFacturacion);

        menuReportesLecturas.setText("Lecturas");

        menuReportesHistorialLecturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesHistorialLecturas.setText("Historial de Lecturas");
        menuReportesHistorialLecturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHistorialLecturasActionPerformed(evt);
            }
        });
        menuReportesLecturas.add(menuReportesHistorialLecturas);

        menuReportesBalanceAntiguedad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/reporte.png"))); // NOI18N
        menuReportesBalanceAntiguedad1.setText("Toma de Lecturas");
        menuReportesBalanceAntiguedad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesBalanceAntiguedad1ActionPerformed(evt);
            }
        });
        menuReportesLecturas.add(menuReportesBalanceAntiguedad1);

        menuReportes.add(menuReportesLecturas);

        menu.add(menuReportes);

        menuAyuda.setText("Ayuda");

        menuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/informacion.png"))); // NOI18N
        menuAcercaDe.setText("Acerca De Payments");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuAcercaDe);

        menu.add(menuAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        
        wdwAyudaAcercaDeInventario AcercaDeInventario = new wdwAyudaAcercaDeInventario();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (AcercaDeInventario.getWidth() / 2);
        int y  = (alto / 2) - (AcercaDeInventario.getHeight() / 2);
        AcercaDeInventario.setVisible(true);
        pnlPrincipal.add(AcercaDeInventario);
        AcercaDeInventario.toFront();
        AcercaDeInventario.setLocation(x, y);
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void menuGeneracionDeCobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGeneracionDeCobrosActionPerformed
        wdwGeneracionDeCobros pantalla = new wdwGeneracionDeCobros();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuGeneracionDeCobrosActionPerformed

    private void menuReportesMaestroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesMaestroUsuariosActionPerformed
        wdwReportesMaestroUsuarios reporte = new wdwReportesMaestroUsuarios();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        
        reporte.setLocation(x, y);
        reporte.setVisible(true);
        pnlPrincipal.add(reporte);
        reporte.toFront();
    }//GEN-LAST:event_menuReportesMaestroUsuariosActionPerformed

    private void menuReportesImpresionRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesImpresionRecibosActionPerformed
  
        wdwReportesImpresionFacturas reporte = new wdwReportesImpresionFacturas ();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesImpresionRecibosActionPerformed

    private void menuReportesAbonosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesAbonosClienteActionPerformed
        wdwReportesAbonosCliente reporte = new wdwReportesAbonosCliente();        
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesAbonosClienteActionPerformed

    private void menuReportesRecibosNoPagadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesRecibosNoPagadosActionPerformed
        wdwReportesRecibosNoPagados reporte = new wdwReportesRecibosNoPagados();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesRecibosNoPagadosActionPerformed

    private void menuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedoresActionPerformed
        wdwCatalogoUsuarios pantalla = new wdwCatalogoUsuarios();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuProveedoresActionPerformed

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed

        wdwCatalogoProductos CatalogoProductos = new wdwCatalogoProductos();
        CatalogoProductos.setVisible(true);
        pnlPrincipal.add(CatalogoProductos);
        CatalogoProductos.toFront();
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        wdwCatalogoClientes pantalla = new wdwCatalogoClientes();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();

    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        wdwCatalogoCategorias pantalla = new wdwCatalogoCategorias();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuCategoriasActionPerformed

    private void menuEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresasActionPerformed
        wdwCatalogoEmpresas pantalla = new wdwCatalogoEmpresas();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuEmpresasActionPerformed

    private void menuPenalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenalizacionActionPerformed
        wdwCatalogoPenalizacion pantalla = new wdwCatalogoPenalizacion();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuPenalizacionActionPerformed

    private void menuIngresarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarSuscripcionActionPerformed
        wdwCatalogoSuscripciones pantalla = new wdwCatalogoSuscripciones();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuIngresarSuscripcionActionPerformed

    private void menuReportesBalanceAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesBalanceAntiguedadActionPerformed
        wdwReportesBalanceAntiguedad reporte = new wdwReportesBalanceAntiguedad();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesBalanceAntiguedadActionPerformed

    private void menuIngresarLecturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarLecturasActionPerformed
        wdwMovimientoIngresoLecturas pantalla = new wdwMovimientoIngresoLecturas();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuIngresarLecturasActionPerformed

    private void menuReportesBalanceAntiguedad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesBalanceAntiguedad1ActionPerformed
       wdwReportesTomaLecturas reporte = new wdwReportesTomaLecturas();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesBalanceAntiguedad1ActionPerformed

    private void menuMovimientoAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimientoAbonosActionPerformed
        wdwAbonosPorCliente ventana = new wdwAbonosPorCliente();
        pnlPrincipal.add(ventana);
        ventana.show();
        ventana.toFront();
    }//GEN-LAST:event_menuMovimientoAbonosActionPerformed

    private void menuReportesImpresionRecibos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesImpresionRecibos1ActionPerformed
        wdwReportesImpresionRecibosCobro reporte = new wdwReportesImpresionRecibosCobro();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesImpresionRecibos1ActionPerformed

    private void menuReportesHistorialLecturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHistorialLecturasActionPerformed
        wdwReportesLecturas reporte = new wdwReportesLecturas();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesHistorialLecturasActionPerformed

    private void menuReportesCierreDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesCierreDiarioActionPerformed
        wdwReportesCierreDiario reporte = new wdwReportesCierreDiario();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesCierreDiarioActionPerformed

    private void menuDescargaLecturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDescargaLecturasActionPerformed
        wdwMovimientoDescargaLecturas pantalla = new wdwMovimientoDescargaLecturas();
        pantalla.setVisible(true);
        pnlPrincipal.add(pantalla);
        pantalla.toFront();
    }//GEN-LAST:event_menuDescargaLecturasActionPerformed

    private void menuReportesMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesMorososActionPerformed
        wdwReportesMorosos reporte = new wdwReportesMorosos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesMorososActionPerformed

    private void menuReportesMorososMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesMorososMesActionPerformed
        wdwReportesMorososMes reporte = new wdwReportesMorososMes();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesMorososMesActionPerformed

    private void menuReportesFacturacionMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesFacturacionMensualActionPerformed
        wdwReportesFacturacionMensual reporte = new wdwReportesFacturacionMensual();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesFacturacionMensualActionPerformed

    private void menuReportesAbonosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesAbonosRealizadosActionPerformed
        wdwReportesAbonosRecibidos reporte = new wdwReportesAbonosRecibidos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesAbonosRealizadosActionPerformed

    private void menuReportesAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesAjustesActionPerformed
        wdwReportesAjustes reporte = new wdwReportesAjustes();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesAjustesActionPerformed

    private void menuPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagosActionPerformed
        wdwContabilidadPagos ContabilidadPagos = new wdwContabilidadPagos();
        ContabilidadPagos.setVisible(true);
        pnlPrincipal.add(ContabilidadPagos);
        ContabilidadPagos.toFront();
    }//GEN-LAST:event_menuPagosActionPerformed

    private void menuReportesPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesPagosActionPerformed
        wdwReportesPagosPorFecha reporte = new wdwReportesPagosPorFecha();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesPagosActionPerformed

    private void menuContabilidadIngresoCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContabilidadIngresoCobroActionPerformed
        wdwContabilidadCobros ContabilidadPagos = new wdwContabilidadCobros();
        ContabilidadPagos.setVisible(true);
        pnlPrincipal.add(ContabilidadPagos);
        ContabilidadPagos.toFront();
    }//GEN-LAST:event_menuContabilidadIngresoCobroActionPerformed

    private void menuReportesCobrosPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesCobrosPorFechaActionPerformed
        wdwReportesCobrosPorFecha reporte = new wdwReportesCobrosPorFecha();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesCobrosPorFechaActionPerformed

    private void menuIngresarSuscripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarSuscripcion1ActionPerformed
        wdwCatalogoCreditos ContabilidadPagos = new wdwCatalogoCreditos();
        ContabilidadPagos.setVisible(true);
        pnlPrincipal.add(ContabilidadPagos);
        ContabilidadPagos.toFront();
    }//GEN-LAST:event_menuIngresarSuscripcion1ActionPerformed

    private void menuReportesCreditosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesCreditosPendientesActionPerformed
        wdwReportesCreditosPendientes reporte = new wdwReportesCreditosPendientes();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) -  (reporte.getHeight() / 2);
        reporte.setLocation(x, y);
        reporte .setVisible(true);
        pnlPrincipal.add(reporte);
        reporte .toFront();
    }//GEN-LAST:event_menuReportesCreditosPendientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenu menuAyuda;
    public static javax.swing.JMenu menuCatalogo;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenu menuContabilidad;
    private javax.swing.JMenuItem menuContabilidadIngresoCobro;
    private javax.swing.JMenuItem menuDescargaLecturas;
    private javax.swing.JMenuItem menuEmpresas;
    private javax.swing.JMenuItem menuGeneracionDeCobros;
    private javax.swing.JMenuItem menuIngresarLecturas;
    private javax.swing.JMenuItem menuIngresarSuscripcion;
    private javax.swing.JMenuItem menuIngresarSuscripcion1;
    public static javax.swing.JMenu menuMovimiento;
    private javax.swing.JMenuItem menuMovimientoAbonos;
    private javax.swing.JMenuItem menuPagos;
    private javax.swing.JMenuItem menuPenalizacion;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuProveedores;
    public static javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuReportesAbonos;
    private javax.swing.JMenuItem menuReportesAbonosCliente;
    private javax.swing.JMenuItem menuReportesAbonosRealizados;
    private javax.swing.JMenuItem menuReportesAjustes;
    private javax.swing.JMenuItem menuReportesBalanceAntiguedad;
    private javax.swing.JMenuItem menuReportesBalanceAntiguedad1;
    private javax.swing.JMenuItem menuReportesCierreDiario;
    private javax.swing.JMenu menuReportesClientes;
    private javax.swing.JMenuItem menuReportesCobrosPorFecha;
    private javax.swing.JMenu menuReportesContabilidad;
    private javax.swing.JMenuItem menuReportesCreditosPendientes;
    private javax.swing.JMenu menuReportesFacturacion;
    private javax.swing.JMenuItem menuReportesFacturacionMensual;
    private javax.swing.JMenuItem menuReportesHistorialLecturas;
    private javax.swing.JMenuItem menuReportesImpresionRecibos;
    private javax.swing.JMenuItem menuReportesImpresionRecibos1;
    private javax.swing.JMenu menuReportesLecturas;
    private javax.swing.JMenuItem menuReportesMaestroUsuarios;
    private javax.swing.JMenuItem menuReportesMorosos;
    private javax.swing.JMenuItem menuReportesMorososMes;
    private javax.swing.JMenuItem menuReportesPagos;
    private javax.swing.JMenuItem menuReportesRecibosNoPagados;
    public static javax.swing.JDesktopPane pnlPrincipal;
    public static javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
