/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoCliente;
import inventory.acceso.Mensaje;
import inventory.objetos.ObjetosCliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class wdwCatalogoClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form wdwIngresoClientes
     */
    public wdwCatalogoClientes() {
        initComponents();
        mostrarRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblIdCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblNitCliente = new javax.swing.JLabel();
        txtNitCliente = new javax.swing.JTextField();
        txtZonaCliente = new javax.swing.JTextField();
        txtDPICliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxDeptoCliente = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtMunicipioCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCiudadCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtColoniaCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAvenidaCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCalleCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumCasaCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMovilCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxEstadoCliente = new javax.swing.JComboBox();
        txtNombreCliente = new javax.swing.JTextField();
        lblIdCliente1 = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        pnlExtra = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/clientes.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));

        pnlEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdCliente.setText("ID Clente");

        txtIdCliente.setBackground(new java.awt.Color(153, 153, 153));
        txtIdCliente.setEditable(false);
        txtIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCliente.setToolTipText("Este campo no se puede editar el programa asigana automaticamente un numero de ID");

        lblNitCliente.setText("No. NIT");

        txtNitCliente.setToolTipText("");

        txtZonaCliente.setToolTipText("");

        txtDPICliente.setToolTipText("");

        jLabel1.setText("No. DPI");

        jLabel2.setText("Depto.");

        cbxDeptoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta Verapaz ", "Baja Verapaz ", "Chimaltenango ", "Chiquimula ", "Petén ", "El Progreso ", "Quiché ", "Escuintla ", "Guatemala ", "Huehuetenango ", "Izabal", "Jalapa ", "Jutiapa ", "Quetzaltenango ", "Retalhuleu ", "Sacatepéquez ", "San Marcos ", "Santa Rosa ", "Sololá ", "Suchitepéquez ", "Totonicapán ", "Zacapa ", " ", " " }));

        jLabel3.setText("Municipio");

        jLabel4.setText("Ciudad");

        jLabel5.setText("Zona");

        jLabel6.setText("Colonia");

        jLabel7.setText("Avenida");

        jLabel8.setText("Calle");

        jLabel9.setText("No. Casa");

        jLabel11.setText("Telefono");

        jLabel12.setText("Celular");

        jLabel13.setText("Correo");

        jLabel14.setText("Estado");

        cbxEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        txtNombreCliente.setToolTipText("");
        txtNombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreClienteFocusGained(evt);
            }
        });

        lblIdCliente1.setText("Nombre");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addGap(21, 21, 21)
                                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCalleCliente)
                                    .addComponent(cbxDeptoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtZonaCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel8)
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addComponent(lblIdCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNitCliente)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNitCliente)
                            .addComponent(txtMunicipioCliente)
                            .addComponent(txtColoniaCliente)
                            .addComponent(txtNumCasaCliente)
                            .addComponent(txtMovilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAvenidaCliente)
                                    .addComponent(cbxEstadoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtDPICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCiudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(lblIdCliente1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCliente)))
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNitCliente)
                        .addComponent(txtNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdCliente)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtDPICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblIdCliente1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxDeptoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtMunicipioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCiudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(6, 6, 6)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZonaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtColoniaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtAvenidaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalleCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtNumCasaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtMovilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbxEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setText("Buscar");

        txtBuscar.setToolTipText("Ingreseel nombre dle cliente a buscar");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBuscar)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir)
                        .addComponent(btnLimpiar)
                        .addComponent(btnModificar)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlExtra.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Otra Dir.");

        javax.swing.GroupLayout pnlExtraLayout = new javax.swing.GroupLayout(pnlExtra);
        pnlExtra.setLayout(pnlExtraLayout);
        pnlExtraLayout.setHorizontalGroup(
            pnlExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtDireccionCliente)
                .addContainerGap())
        );
        pnlExtraLayout.setVerticalGroup(
            pnlExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Mensaje mensaje = new Mensaje();
    AccesoCliente acceso = new AccesoCliente();
    ObjetosCliente cliente = new ObjetosCliente();

    private void limpiarCampos() {
        btnGuardar.setEnabled(true);
        txtIdCliente.setText("");
        txtNitCliente.setText("");
        txtDPICliente.setText("");
        txtNombreCliente.setText("");
        txtMunicipioCliente.setText("");
        txtCiudadCliente.setText("");
        txtZonaCliente.setText("");
        txtColoniaCliente.setText("");
        txtAvenidaCliente.setText("");
        txtCalleCliente.setText("");
        txtNumCasaCliente.setText("");
        txtDireccionCliente.setText("");
        txtTelefonoCliente.setText("");
        txtMovilCliente.setText("");
        txtCorreoCliente.setText("");
    }
    
    private String convertirEstado(String x) {
        String valor = "";
        if (x.equals("A")) {
            valor = "Activo";
        }
        if (x.equals("I")) {
            valor = "Inactivo";
        }
        if (x.equals("Activo")) {
            valor = "A";
        }
        if (x.equals("Inactivo")) {
            valor = "I";
        }
        return valor;
    }

    private void mostrarRegistros() {

        DefaultTableModel tabla = new DefaultTableModel();
        ArrayList<ObjetosCliente> lista = new ArrayList();

        try {
            lista = acceso.listarClientes();
        } catch (Error error) {
            mensaje.manipulacionExcepciones("critico", "No se a podido listar los registros");
        }

        if (lista.isEmpty()) {
            mensaje.manipulacionExcepciones("critico", "No existen datos almacenados");
        } else {
            tabla.addColumn("ID Cliente");
            tabla.addColumn("Numero DPI");
            tabla.addColumn("NIT");
            tabla.addColumn("Nombre");
            tabla.addColumn("Departamento");
            tabla.addColumn("Municipio");
            tabla.addColumn("Ciudad");
            tabla.addColumn("Zona");
            tabla.addColumn("Colonia");
            tabla.addColumn("Avenida");
            tabla.addColumn("Calle");
            tabla.addColumn("Numero Casa");
            tabla.addColumn("Direccion Alterna");
            tabla.addColumn("Telefono");
            tabla.addColumn("Movil");
            tabla.addColumn("Correo Electronico");
            tabla.addColumn("Estado");

            tabla.setRowCount(lista.size());
            int fila = 0;

            for (ObjetosCliente x : lista) {
                tabla.setValueAt(x.getId_cliente(), fila, 0);
                tabla.setValueAt(x.getDpi_cliente(), fila, 1);
                tabla.setValueAt(x.getNit_cliente(), fila, 2);
                tabla.setValueAt(x.getNombre_cliente(), fila, 3);
                tabla.setValueAt(x.getDepto_cliente(), fila, 4);
                tabla.setValueAt(x.getMunicipio_cliente(), fila, 5);
                tabla.setValueAt(x.getCiudad_cliente(), fila, 6);
                tabla.setValueAt(x.getZona_cliente(), fila, 7);
                tabla.setValueAt(x.getColonia_cliente(), fila, 8);
                tabla.setValueAt(x.getAvenida_cliente(), fila, 9);
                tabla.setValueAt(x.getCalle_cliente(), fila, 10);
                tabla.setValueAt(x.getNum_casa_cliente(), fila, 11);
                tabla.setValueAt(x.getDireccion_cliente(), fila, 12);
                tabla.setValueAt(x.getTelefono_cliente(), fila, 13);
                tabla.setValueAt(x.getMovil_cliente(), fila, 14);
                tabla.setValueAt(x.getCorreo_cliente(), fila, 15);
                tabla.setValueAt(convertirEstado(x.getEstado_cliente()), fila, 16);
                fila++;
            }

            tblCliente.setModel(tabla);
        }
    }

    private void buscarRegistros() {
        
        DefaultTableModel tabla = new DefaultTableModel();
        ArrayList<ObjetosCliente> lista = new ArrayList();

        try {
            lista = acceso.buscarClientes(txtBuscar.getText().toUpperCase());
        } catch (Error error) {
            mensaje.manipulacionExcepciones("critico", "No se a podido listar los registros");
        }

        if (lista.isEmpty()) {
            mensaje.manipulacionExcepciones("critico", "No existen datos almacenados");
        } else {
            tabla.addColumn("ID Cliente");
            tabla.addColumn("Numero DPI");
            tabla.addColumn("NIT");
            tabla.addColumn("Nombre");
            tabla.addColumn("Departamento");
            tabla.addColumn("Municipio");
            tabla.addColumn("Ciudad");
            tabla.addColumn("Zona");
            tabla.addColumn("Colonia");
            tabla.addColumn("Avenida");
            tabla.addColumn("Calle");
            tabla.addColumn("Numero Casa");
            tabla.addColumn("Direccion Alterna");
            tabla.addColumn("Telefono");
            tabla.addColumn("Movil");
            tabla.addColumn("Correo Electronico");
            tabla.addColumn("Estado");

            tabla.setRowCount(lista.size());
            int fila = 0;

            for (ObjetosCliente x : lista) {
                tabla.setValueAt(x.getId_cliente(), fila, 0);
                tabla.setValueAt(x.getDpi_cliente(), fila, 1);
                tabla.setValueAt(x.getNit_cliente(), fila, 2);
                tabla.setValueAt(x.getNombre_cliente(), fila, 3);
                tabla.setValueAt(x.getDepto_cliente(), fila, 4);
                tabla.setValueAt(x.getMunicipio_cliente(), fila, 5);
                tabla.setValueAt(x.getCiudad_cliente(), fila, 6);
                tabla.setValueAt(x.getZona_cliente(), fila, 7);
                tabla.setValueAt(x.getColonia_cliente(), fila, 8);
                tabla.setValueAt(x.getAvenida_cliente(), fila, 9);
                tabla.setValueAt(x.getCalle_cliente(), fila, 10);
                tabla.setValueAt(x.getNum_casa_cliente(), fila, 11);
                tabla.setValueAt(x.getDireccion_cliente(), fila, 12);
                tabla.setValueAt(x.getTelefono_cliente(), fila, 13);
                tabla.setValueAt(x.getMovil_cliente(), fila, 14);
                tabla.setValueAt(x.getCorreo_cliente(), fila, 15);
                tabla.setValueAt(convertirEstado(x.getEstado_cliente()), fila, 16);
                fila++;
            }

            tblCliente.setModel(tabla);
        }
    }

    private void guardarRegistros() {
        cliente.setDpi_cliente(txtDPICliente.getText());
        cliente.setNit_cliente(txtNitCliente.getText());
        cliente.setNombre_cliente(txtNombreCliente.getText());
        cliente.setDepto_cliente(cbxDeptoCliente.getSelectedItem().toString());
        cliente.setMunicipio_cliente(txtMunicipioCliente.getText());
        cliente.setCiudad_cliente(txtCiudadCliente.getText());
        cliente.setZona_cliente(txtZonaCliente.getText());
        cliente.setColonia_cliente(txtColoniaCliente.getText());
        cliente.setAvenida_cliente(txtAvenidaCliente.getText());
        cliente.setCalle_cliente(txtCalleCliente.getText());
        cliente.setNum_casa_cliente(txtNumCasaCliente.getText());
        cliente.setDireccion_cliente(txtDireccionCliente.getText());
        cliente.setTelefono_cliente(Integer.parseInt(txtTelefonoCliente.getText()));
        cliente.setMovil_cliente(Integer.parseInt(txtMovilCliente.getText()));
        cliente.setCorreo_cliente(txtCorreoCliente.getText());
        cliente.setEstado_cliente(convertirEstado(cbxEstadoCliente.getSelectedItem().toString()));
        acceso.insertarCliente(cliente, Inventory.txtUsuario.getText());
    }
    
    private void actualizarRegistos(){
        cliente.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        cliente.setDpi_cliente(txtDPICliente.getText());
        cliente.setNit_cliente(txtNitCliente.getText());
        cliente.setNombre_cliente(txtNombreCliente.getText());
        cliente.setDepto_cliente(cbxDeptoCliente.getSelectedItem().toString());
        cliente.setMunicipio_cliente(txtMunicipioCliente.getText());
        cliente.setCiudad_cliente(txtCiudadCliente.getText());
        cliente.setZona_cliente(txtZonaCliente.getText());
        cliente.setColonia_cliente(txtColoniaCliente.getText());
        cliente.setAvenida_cliente(txtAvenidaCliente.getText());
        cliente.setCalle_cliente(txtCalleCliente.getText());
        cliente.setNum_casa_cliente(txtNumCasaCliente.getText());
        cliente.setDireccion_cliente(txtDireccionCliente.getText());
        cliente.setTelefono_cliente(Integer.parseInt(txtTelefonoCliente.getText()));
        cliente.setMovil_cliente(Integer.parseInt(txtMovilCliente.getText()));
        cliente.setCorreo_cliente(txtCorreoCliente.getText());
        cliente.setEstado_cliente(convertirEstado(cbxEstadoCliente.getSelectedItem().toString()));
        acceso.actualizarCliente(cliente, Inventory.txtUsuario.getText());
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarRegistros();
        mostrarRegistros();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarRegistros();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        actualizarRegistos();
        mostrarRegistros();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        btnGuardar.setEnabled(false);
        txtIdCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0)));
        txtDPICliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 1)));
        txtNitCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 2)));
        txtNombreCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 3)));
        cbxDeptoCliente.setSelectedItem(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 4)));
        txtMunicipioCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 5)));
        txtCiudadCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 6)));
        txtZonaCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 7)));
        txtColoniaCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 8)));
        txtAvenidaCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 9)));
        txtCalleCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 10)));
        txtNumCasaCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 11)));
        txtDireccionCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 12)));
        txtTelefonoCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 13)));
        txtMovilCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 14)));
        txtCorreoCliente.setText(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 15)));
        cbxEstadoCliente.setSelectedItem(String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 16))); 
    }//GEN-LAST:event_tblClienteMouseClicked

    private void txtNombreClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreClienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxDeptoCliente;
    private javax.swing.JComboBox cbxEstadoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdCliente1;
    private javax.swing.JLabel lblNitCliente;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlExtra;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtAvenidaCliente;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCalleCliente;
    private javax.swing.JTextField txtCiudadCliente;
    private javax.swing.JTextField txtColoniaCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDPICliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMovilCliente;
    private javax.swing.JTextField txtMunicipioCliente;
    private javax.swing.JTextField txtNitCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumCasaCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtZonaCliente;
    // End of variables declaration//GEN-END:variables
}
