/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoCliente;
import inventory.acceso.AccesoCredito;
import inventory.acceso.AccesoProducto;
import inventory.acceso.AccesoSuscripcion;
import inventory.acceso.Mensaje;
import inventory.objetos.ObjetosCliente;
import inventory.objetos.ObjetosCredito;
import inventory.objetos.ObjetosProducto;
import inventory.objetos.ObjetosSuscripcion;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import inventory.servicios.*;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */
public class wdwCatalogoCreditos extends javax.swing.JInternalFrame {

    Mensaje mensaje = new Mensaje();
    ObjetosSuscripcion suscripcion = new ObjetosSuscripcion();
    ObjetosCredito credito = new ObjetosCredito();
    AccesoSuscripcion acceso_suscripcion = new AccesoSuscripcion();
    AccesoCredito acceso_credito = new AccesoCredito();
    ServicioOperacionesMatematicas matematicas = new ServicioOperacionesMatematicas();

    /**
     * Creates new form wdwCatalogoProductos
     */
    public wdwCatalogoCreditos() {
        initComponents();
        cargarSuscripciones();
        buscarRegistros();
    }
    
    private void buscarRegistros() {

        DefaultTableModel tabla = new DefaultTableModel();
        ArrayList<ObjetosCredito> lista_creditos = new ArrayList();

        lista_creditos = acceso_credito.listarCredito(txtBuscar.getText());

        tabla.addColumn("ID Credito");
        tabla.addColumn("ID Suscripcion");
        tabla.addColumn("Cliente");
        tabla.addColumn("Direccion");
        tabla.addColumn("Descripcion");
        tabla.addColumn("Monto");
        tabla.addColumn("No. Cuotas");
        tabla.addColumn("Monto de Cuotas");
        tabla.addColumn("Saldo");
        tabla.addColumn("Abonado");
        tabla.addColumn("Estado");

        tabla.setRowCount(lista_creditos.size());
        int fila = 0;

        for (ObjetosCredito x : lista_creditos) {
            tabla.setValueAt(x.getId_credito(), fila, 0);
            tabla.setValueAt(x.getId_suscripcion(), fila, 1);
            tabla.setValueAt(x.getNombre_cliente(), fila, 2);
            tabla.setValueAt(x.getDireccion_suscripcion(), fila, 3);
            tabla.setValueAt(x.getDescripcion_credito(), fila, 4);
            tabla.setValueAt(x.getMonto_credito(), fila, 5);
            tabla.setValueAt(x.getCantidad_cuotas_credito(), fila, 6);
            tabla.setValueAt(x.getMonto_cuota_credito(), fila, 7);
            tabla.setValueAt(x.getSaldo_credito(), fila, 8);
            tabla.setValueAt(x.getAbonado_credito(), fila, 9);
            tabla.setValueAt(x.getEstado_credito(), fila, 10);
            fila++;
        }

        tblCreditos.setModel(tabla);
    }

    private void guardarRegistros() {
        credito.setId_credito(0);
        credito.setId_suscripcion(Integer.parseInt(cbxIdSuscripcion.getSelectedItem().toString()));
        credito.setNombre_cliente(cbxSuscripcion.getSelectedItem().toString());
        credito.setDireccion_suscripcion(txtDireccion.getText());
        credito.setDescripcion_credito(txtDescripcion.getText());
        credito.setMonto_credito(Double.parseDouble(txtMonto.getText()));
        credito.setCantidad_cuotas_credito(Integer.parseInt(txtNoCuotas.getText()));
        credito.setMonto_cuota_credito(Double.parseDouble(txtMontoCuota.getText()));
        credito.setSaldo_credito(Double.parseDouble(txtSaldo.getText()));
        credito.setAbonado_credito(Double.parseDouble(txtAbonado.getText()));
        credito.setEstado_credito(cbxEstado.getSelectedItem().toString());
        acceso_credito.insertarCredito(credito, Inventory.txtUsuario.getText());
    }


    private void limpiarCampos() {
        btnGuardar.setEnabled(true);
        txtIdCredito.setText("");
        //txtCantidadSuscripciones.setText("");
        txtDescripcion.setText("");
        txtDireccion.setText("");
        txtMonto.setText("");
        txtNoCuotas.setText("");
        txtMontoCuota.setText("");
        txtSaldo.setText("");
        txtAbonado.setText("");
    }
    
    
    private void cargarSuscripciones() {
        ArrayList<ObjetosSuscripcion> lista = new ArrayList();
        lista =  acceso_suscripcion.listarSuscripcionesSinRepetir();
        for(ObjetosSuscripcion x : lista){
            cbxSuscripcion.addItem(x.getNombre_cliente());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblIdProducto = new javax.swing.JLabel();
        txtIdCredito = new javax.swing.JTextField();
        lblMarcaProducto = new javax.swing.JLabel();
        lblDescProducto = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblPrecioEstProducto = new javax.swing.JLabel();
        txtNoCuotas = new javax.swing.JTextField();
        lblMinimoProducto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        cbxSuscripcion = new javax.swing.JComboBox();
        txtSaldo = new javax.swing.JTextField();
        lblPrecioEstProducto1 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtMontoCuota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAbonado = new javax.swing.JTextField();
        txtCantidadSuscripciones = new javax.swing.JTextField();
        lblMinimoProducto1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        cbxIdSuscripcion = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAbonar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCreditos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingresar de Credito");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/archivo.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1200, 550));
        setMinimumSize(new java.awt.Dimension(925, 550));
        setPreferredSize(new java.awt.Dimension(925, 550));

        pnlEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdProducto.setText("ID Credito");

        txtIdCredito.setBackground(new java.awt.Color(153, 153, 153));
        txtIdCredito.setEditable(false);
        txtIdCredito.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCredito.setToolTipText("");

        lblMarcaProducto.setText("ID Sucripcion");

        lblDescProducto.setText("Direccion");
        lblDescProducto.setToolTipText("");

        txtDireccion.setBackground(new java.awt.Color(153, 153, 153));
        txtDireccion.setEditable(false);
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setToolTipText("");

        lblPrecioEstProducto.setText("Monto");

        txtNoCuotas.setToolTipText("");
        txtNoCuotas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NoCuotasLostFocus(evt);
            }
        });

        lblMinimoProducto.setText("Estado Credito");

        txtMonto.setToolTipText("");

        cbxSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSuscripcionActionPerformed(evt);
            }
        });

        txtSaldo.setBackground(new java.awt.Color(153, 153, 153));
        txtSaldo.setEditable(false);
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo.setToolTipText("");

        lblPrecioEstProducto1.setText("No. Cuotas");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendiente" }));

        jLabel2.setText("Monto Cuota");

        txtMontoCuota.setBackground(new java.awt.Color(153, 153, 153));
        txtMontoCuota.setEditable(false);
        txtMontoCuota.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Abonado");

        txtAbonado.setToolTipText("");

        txtCantidadSuscripciones.setBackground(new java.awt.Color(153, 153, 153));
        txtCantidadSuscripciones.setEditable(false);
        txtCantidadSuscripciones.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidadSuscripciones.setToolTipText("");

        lblMinimoProducto1.setText("Descripcion");

        txtDescripcion.setToolTipText("");

        cbxIdSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdSuscripcionActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioEstProducto)
                    .addComponent(lblIdProducto)
                    .addComponent(lblDescProducto))
                .addGap(20, 20, 20)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecioEstProducto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                    .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(txtIdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMarcaProducto)
                        .addGap(10, 10, 10)
                        .addComponent(txtCantidadSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxIdSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSuscripcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimoProducto)
                    .addComponent(lblMinimoProducto1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcion)
                    .addComponent(cbxEstado, 0, 127, Short.MAX_VALUE)
                    .addComponent(txtAbonado))
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProducto)
                    .addComponent(txtIdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarcaProducto)
                    .addComponent(cbxSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimoProducto1)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxIdSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescProducto)
                    .addComponent(lblMinimoProducto)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioEstProducto)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioEstProducto1)
                    .addComponent(txtNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setText("Buscar");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAbonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/coins.png"))); // NOI18N
        btnAbonar.setText("Abonar");
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.setToolTipText("Ingrese el nombre del producto que desea buscar");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbonar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBuscar)
                        .addComponent(btnSalir)
                        .addComponent(btnLimpiar)
                        .addComponent(btnAbonar)
                        .addComponent(btnGuardar)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCreditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCreditos.getTableHeader().setReorderingAllowed(false);
        tblCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCreditosCllicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCreditos);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarRegistros();
        buscarRegistros();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarRegistros();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        
        //abrir pantalla para abono al credito seleccionado
        wdwContabilidadAbonoCredito abono_credito = new wdwContabilidadAbonoCredito();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (abono_credito.getWidth() / 2);
        int y  = (alto / 2) -  (abono_credito.getHeight() / 2);
        abono_credito.setLocation(x, y);
        abono_credito.setVisible(true);
        Inventory.pnlPrincipal.add(abono_credito);
        abono_credito.toFront();
        
        //consultar el numero de cuotas pendientes
        int cuotas_realizadas = acceso_credito.cuotasRecibidas(txtIdCredito.getText());
        Double v_saldo = Double.parseDouble(txtSaldo.getText()) - Double.parseDouble(txtMontoCuota.getText());
        
        //enviar parametros a la pantalla
        wdwContabilidadAbonoCredito.txtNombre.setText(cbxSuscripcion.getSelectedItem().toString());
        wdwContabilidadAbonoCredito.txtCantidadCuotas.setText("1");
        wdwContabilidadAbonoCredito.txtMonto.setText(txtMontoCuota.getText());
        wdwContabilidadAbonoCredito.txtDireecion.setText(txtDireccion.getText());
        wdwContabilidadAbonoCredito.txtMotivo.setText("ABONO CONTADOR NO. " + ( cuotas_realizadas + 1 ) + " DE " +  txtNoCuotas.getText());
        wdwContabilidadAbonoCredito.txtSaldo.setText(String.valueOf(v_saldo));
        wdwContabilidadAbonoCredito.txtIdCredito.setText(txtIdCredito.getText());
        wdwContabilidadAbonoCredito.txtCuotasPendientes.setText(String.valueOf(cuotas_realizadas + 1));
        wdwContabilidadAbonoCredito.txtCuotasTotales.setText(String.valueOf(txtNoCuotas.getText()));
        
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
//GEN-FIRST:event_txtIdProveedorFocusLost
//GEN-LAST:event_txtIdProveedorFocusLost

    private void tblCreditosCllicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCreditosCllicked
        btnGuardar.setEnabled(false);
        txtIdCredito.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 0).toString());
        cbxIdSuscripcion.setSelectedItem(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 1).toString());
        cbxSuscripcion.setSelectedItem(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 2));
        txtDireccion.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 3).toString());
        txtDescripcion.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 4).toString());
        txtMonto.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 5).toString());
        txtNoCuotas.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 6).toString());
        txtMontoCuota.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 7).toString());
        txtSaldo.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 8).toString());
        txtAbonado.setText(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 9).toString());
        cbxEstado.setSelectedItem(tblCreditos.getValueAt(tblCreditos.getSelectedRow(), 10));
    }//GEN-LAST:event_tblCreditosCllicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbxSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSuscripcionActionPerformed
        ArrayList<ObjetosSuscripcion> lista = new ArrayList();
        lista = acceso_suscripcion.mostrarSuscripcionesPorCliente(cbxSuscripcion.getSelectedItem().toString());
        txtCantidadSuscripciones.setText(String.valueOf(lista.size()));
        cbxIdSuscripcion.removeAllItems();
        for (ObjetosSuscripcion x : lista) {
            cbxIdSuscripcion.addItem(x.getId_suscripcion());  
        }
    }//GEN-LAST:event_cbxSuscripcionActionPerformed

    private void NoCuotasLostFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NoCuotasLostFocus
        Double resultado = Double.parseDouble(txtMonto.getText()) / Double.parseDouble(txtNoCuotas.getText());
        txtMontoCuota.setText(String.valueOf(matematicas.redondear(resultado, 2)));
        txtSaldo.setText(txtMonto.getText());
    }//GEN-LAST:event_NoCuotasLostFocus

    private void cbxIdSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdSuscripcionActionPerformed
        //buscar la direccion de las suscripcion
        ArrayList<ObjetosSuscripcion> lista = new ArrayList<>();
        if(cbxIdSuscripcion.getItemCount() > 0) {
            lista = acceso_suscripcion.buscarInformacionSuscripcion(cbxIdSuscripcion.getSelectedItem().toString());
            for(ObjetosSuscripcion x : lista) {
                txtDireccion.setText(x.getDireccion_suscripcion());
            }
        }
    }//GEN-LAST:event_cbxIdSuscripcionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JComboBox cbxIdSuscripcion;
    private javax.swing.JComboBox cbxSuscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDescProducto;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblMarcaProducto;
    private javax.swing.JLabel lblMinimoProducto;
    private javax.swing.JLabel lblMinimoProducto1;
    private javax.swing.JLabel lblPrecioEstProducto;
    private javax.swing.JLabel lblPrecioEstProducto1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JTable tblCreditos;
    private javax.swing.JTextField txtAbonado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidadSuscripciones;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCredito;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMontoCuota;
    private javax.swing.JTextField txtNoCuotas;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}