/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.vistas;

import inventory.acceso.AccesoUsuario;
import inventory.acceso.Mensaje;
import inventory.objetos.ObjetosUsuario;
import java.util.ArrayList;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class wdwIngresoDeUsuario extends javax.swing.JInternalFrame {

    Mensaje mensaje = new Mensaje();
    AccesoUsuario Usuario = new AccesoUsuario();

    /**
     * Creates new form wdwIngresoDeUsuario
     */
    public wdwIngresoDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Ingreso de Usuario");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/logotipo.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(300, 200));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(300, 200));

        pnlUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setText("Usuario");

        txtContrasenia.setToolTipText("Ingresar clave acepta mayusculas y minusculas");
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseniaKeyPressed(evt);
            }
        });

        txtUsuario.setToolTipText("Ingresar nombre de usuario");

        lblClave.setText("Clave");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContrasenia)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblClave))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/eliminar_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 72, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comprobarUsuario() {

        ArrayList<ObjetosUsuario> lista = new ArrayList<>();
        AccesoUsuario acceso = new AccesoUsuario();
        lista = acceso.ingresoUsuario(txtUsuario.getText(), txtContrasenia.getText());

        if (lista.size() == 0) {
            mensaje.manipulacionExcepciones("critico", "El usuario y la contraseña son incorrectos");
        } else {
            if (lista.size() > 1) {
                mensaje.manipulacionExcepciones("critico", "Exixten mas de un usuario con estas credenciales, verifique");
            } else {

                Inventory.txtUsuario.setText(txtUsuario.getText());

                for (ObjetosUsuario x : lista) {
                    if (x.getTipo_usuario().equals("Administrador")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menu.setVisible(true);
                        Inventory.menuReportes.setVisible(true);
                        this.dispose();
                    }

                    if (x.getTipo_usuario().equals("Jefe Sucursal")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuReportes.setVisible(true);
                        this.dispose();
                    }

                    if (x.getTipo_usuario().equals("Secretaria")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(true);
                        Inventory.menuReportes.setVisible(false);
                        this.dispose();
                    }

                    if (x.getTipo_usuario().equals("Cajero")) {
                        Inventory.menu.setVisible(true);
                        Inventory.menuMovimiento.setVisible(true);
                        Inventory.menuCatalogo.setVisible(false);
                        Inventory.menuReportes.setVisible(false);
                        this.dispose();
                    }
                }
            }
        }

        txtContrasenia.setText("");
        txtUsuario.setText("");
        txtUsuario.requestFocus();
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtUsuario.getText().equals("admin") && txtContrasenia.getText().equals("Derwin2012mg")) {
            Inventory.menu.setVisible(true);
            Inventory.txtUsuario.setText("admin");
            this.dispose();
        } else {
            comprobarUsuario();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseniaKeyPressed
        if (evt.getKeyCode() == 10) {
            comprobarUsuario();
        }
    }//GEN-LAST:event_txtContraseniaKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
