/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package inventory.vistas;
import inventory.acceso.*;
import inventory.librerias.LeerJSON;
import inventory.objetos.ObjetosCliente;
import inventory.objetos.ObjetosLectura;
import inventory.objetos.ObjetosProducto;
import inventory.objetos.ObjetosSuscripcion;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */
public class wdwMovimientoDescargaLecturas extends javax.swing.JInternalFrame {

    Mensaje mensaje = new Mensaje();
    ObjetosLectura lectura = new ObjetosLectura();
    ObjetosProducto servicio = new ObjetosProducto();
    ObjetosCliente cliente = new ObjetosCliente();
    ObjetosSuscripcion suscripcion = new ObjetosSuscripcion();
    AccesoLectura acceso_lectura = new AccesoLectura();
    AccesoProducto acceso_servicio = new AccesoProducto();
    AccesoCliente acceso_cliente = new AccesoCliente();
    AccesoSuscripcion acceso_suscripcion = new AccesoSuscripcion();
    ArrayList<ObjetosLectura> listado = new ArrayList();

    public wdwMovimientoDescargaLecturas() {
        initComponents();
        cargarServicios();
    }

    private String convertirEstado(String x) {

        String valor = "";

        if (x.equals("A")) {
            valor = "Activo";
        }
        if (x.equals("I")) {
            valor = "Inactivo";
        }
        if (x.equals("C")) {
            valor = "Cancelado";
        }
        if (x.equals("P")) {
            valor = "Pendiente";
        }
        if (x.equals("G")) {
            valor = "Generado";
        }
        if (x.equals("Activo")) {
            valor = "A";
        }
        if (x.equals("Inactivo")) {
            valor = "I";
        }
        if (x.equals("Cancelado")) {
            valor = "C";
        }
        if (x.equals("Pendiente")) {
            valor = "P";
        }
        if (x.equals("Generado")) {
            valor = "G";
        }

        return valor;

    }

    private void guardarRegistros() {
        //variable que almacena los registros almacenados
        int registros_guardados = 0;
        //recorrer la tabla para guardar todos los registros
        for (int x = 0; x < listado.size(); x++) {
            try {
                //crear objeto con la informacion segun la descarga
                lectura.setId_suscripcion(Integer.parseInt(tblLecturas.getValueAt(x, 1).toString()));
                lectura.setAnio_lectura(Integer.parseInt(tblLecturas.getValueAt(x, 2).toString()));
                lectura.setMes_lectura(Integer.parseInt(tblLecturas.getValueAt(x, 3).toString()));
                lectura.setAnterior_lectura(Integer.parseInt(tblLecturas.getValueAt(x, 4).toString()));
                lectura.setNueva_lectura(Integer.parseInt(tblLecturas.getValueAt(x, 5).toString()));
                lectura.setEstado_lectura("A");
                acceso_lectura.insertarLectura(lectura, "webservice");
                System.out.println("Guardada: " + tblLecturas.getValueAt(x, 0) + " Suscripcion: " + tblLecturas.getValueAt(x, 1));
                registros_guardados++;
            } catch (Exception e) {
                System.out.println("Error al guardar: " + tblLecturas.getValueAt(x, 0) + " Suscripcion: " + tblLecturas.getValueAt(x, 1));
            }
        }
        mensaje.manipulacionExcepciones("informacion", "Registros guardados " + registros_guardados);
    }

    private void limpiarCampos() {
        btnGuardar.setEnabled(true);
        txtIdServicio.setText("");
        txtMesLectura.setText("");
        txtAnioLectura.setText("");
    }

    private void cargarServicios() {
        ArrayList<ObjetosProducto> lista = new ArrayList();
        lista = acceso_servicio.mostrarServicios();
        for (ObjetosProducto x : lista) {
            cbxServicio.addItem(x.getNombre_servicio());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEncabezado = new javax.swing.JPanel();
        lblMarcaProducto = new javax.swing.JLabel();
        lblDescProducto = new javax.swing.JLabel();
        txtMesLectura = new javax.swing.JTextField();
        txtIdServicio = new javax.swing.JTextField();
        cbxServicio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtAnioLectura = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnDescarga = new javax.swing.JButton();
        txtJSON = new javax.swing.JTextField();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLecturas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Descargar Lecturas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/nuevo.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(775, 550));
        setMinimumSize(new java.awt.Dimension(775, 550));
        setPreferredSize(new java.awt.Dimension(775, 550));

        pnlEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMarcaProducto.setText("Servicio");

        lblDescProducto.setText("Mes");
        lblDescProducto.setToolTipText("");

        txtMesLectura.setToolTipText("Ingrese la descripcion del producto");

        txtIdServicio.setBackground(new java.awt.Color(102, 102, 102));
        txtIdServicio.setEditable(false);
        txtIdServicio.setForeground(new java.awt.Color(255, 255, 255));
        txtIdServicio.setToolTipText("Ingrese la marca del Producto");

        cbxServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxServicioActionPerformed(evt);
            }
        });

        jLabel2.setText("Año");

        txtAnioLectura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioLecturaLostFocus(evt);
            }
        });

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMesLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnioLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMarcaProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMesLectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescProducto)
                    .addComponent(jLabel2)
                    .addComponent(txtAnioLectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarcaProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnDescarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/imagenes/exportar.png"))); // NOI18N
        btnDescarga.setText("Descargar");
        btnDescarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargaActionPerformed(evt);
            }
        });

        txtJSON.setBackground(new java.awt.Color(102, 102, 102));
        txtJSON.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtJSON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDescarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar)
                    .addComponent(btnDescarga)
                    .addComponent(txtJSON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblLecturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLecturas.getTableHeader().setReorderingAllowed(false);
        tblLecturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLecturasCllicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLecturas);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
//GEN-FIRST:event_txtIdProveedorFocusLost
//GEN-LAST:event_txtIdProveedorFocusLost

    private void tblLecturasCllicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLecturasCllicked
    }//GEN-LAST:event_tblLecturasCllicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbxServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxServicioActionPerformed
        ArrayList<ObjetosProducto> lista = new ArrayList();
        lista = acceso_servicio.buscarServiciosPorNombre(cbxServicio.getSelectedItem().toString());
        for (ObjetosProducto x : lista) {
            txtIdServicio.setText(String.valueOf(x.getId_servicio()));
        }
    }//GEN-LAST:event_cbxServicioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //pedir confirmacion para almacenar los registros
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea trasladar esta informacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            guardarRegistros();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtAnioLecturaLostFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioLecturaLostFocus
    }//GEN-LAST:event_txtAnioLecturaLostFocus

    private void btnDescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargaActionPerformed

        //variables para el servicio web
        String anio = txtAnioLectura.getText();
        String mes = txtMesLectura.getText();
        String ser = txtIdServicio.getText();
        String empresa = "Oportunos";

        try {
            java.net.URL url = new java.net.URL("http://www.oportunosgt.com/payments/services/ejecutar.php?P_FUNCTION=fn_prueba_descarga&P_PARAMETERS='" + empresa + "'," + ser + "," + anio + "," + mes);
            System.out.println("URL: " + "http://www.oportunosgt.com/payments/services/ejecutar.php?P_FUNCTION=fn_prueba_descarga&P_PARAMETERS='" + empresa + "'," + ser + "," + anio + "," + mes);
            java.net.URLConnection con = url.openConnection();
            InputStream s = con.getInputStream();
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(s));
            System.out.println("Contenido Pagina Web:");
            txtJSON.setText("Datos Obtenidos");
            LeerJSON leer = new LeerJSON();
            listado = leer.obtenerJSON(bufferedReader.readLine());
        } catch (java.net.MalformedURLException e) {
            mensaje.manipulacionExcepciones("critico", e.getMessage());
        } catch (IOException e) {
            mensaje.manipulacionExcepciones("critico", e.getMessage());
        }
        
        //mostrar el listado descargado en pantalla
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("ID Lectura");
        tabla.addColumn("ID Suscripcion");
        tabla.addColumn("Año");
        tabla.addColumn("Mes");
        tabla.addColumn("Lectura Anterior");
        tabla.addColumn("Lectura Nueva");
        tabla.addColumn("Consumo Total");
        tabla.setRowCount(listado.size());

        System.out.println("Objetos Descargados: " + listado.size());

        int fila = 0;

        for (ObjetosLectura x : listado) {
            try {
                tabla.setValueAt(fila + 1, fila, 0);
                tabla.setValueAt(x.getId_suscripcion(), fila, 1);
                tabla.setValueAt(x.getAnio_lectura(), fila, 2);
                tabla.setValueAt(x.getMes_lectura(), fila, 3);
                tabla.setValueAt(x.getAnterior_lectura(), fila, 4);
                tabla.setValueAt(x.getNueva_lectura(), fila, 5);
                tabla.setValueAt(x.getNueva_lectura() - x.getAnterior_lectura(), fila, 6);
                fila++;
            } catch (Exception e) {
                System.out.println("Error al mostrar valor de la suscripcion " + x.getId_suscripcion() + ": " + e.getMessage());
            }
        }

        tblLecturas.setModel(tabla);
    }//GEN-LAST:event_btnDescargaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescarga;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxServicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescProducto;
    private javax.swing.JLabel lblMarcaProducto;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JTable tblLecturas;
    private javax.swing.JTextField txtAnioLectura;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtJSON;
    private javax.swing.JTextField txtMesLectura;
    // End of variables declaration//GEN-END:variables
}